name: app
type: php:7.0
build:
  flavor: composer
disk: 4096
runtime:
  extensions:
    - pdo_pgsql
  sizing_hints:
    request_memory: 16

web:
  locations:
    "/":
      root: "app"
      passthru: "/index.php"
      index:
        - index.php
      allow: true

relationships:
  database: "pgsql:postgresql"

mounts:
  "cache/views": "shared:files/view_cache"
  "cache/http": "shared:files/http_cache"
  "Dropbox": "shared:files/dropbox"
  ".dropbox": "shared:files/dropbox-meta"

hooks:
  build: |
    wget "https://www.dropbox.com/download?plat=lnx.x86_64" -O archive.tar
    tar xzvf archive.tar && rm archive.tar