name: app
type: php:7.0
build:
  flavor: composer
disk: 4096

web:
  locations:
    "/":
      root: "app"
      passthru: "/index.php"
      index:
        - index.php
      allow: true

relationships:
  database: "pgsql:postgresql"

mounts:
  "cache/views": "shared:files/view_cache"
  "cache/http": "shared:files/http_cache"