name: app
type: php:7.0
build:
  flavor: composer
disk: 4096
runtime:
  extensions:
    - pdo_pgsql
  sizing_hints:
    request_memory: 16

dependencies:
  python:
    pip: "*"
  ruby: 
    sass: "3.2.14"
    compass: "0.12.2"
  nodejs:
    grunt: "*"

web:
  commands:
    start: |
      ~/.dropbox-dist/dropboxd >/dev/null 2>&1 &
      /usr/sbin/php-fpm7.0
  locations:
    "/":
      root: "app"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
    "/uploads":
      root: "Dropbox/ibd_website_images"
      passthru: false
      allow: true
      scripts: false

relationships:
  database: "pgsql:postgresql"

mounts:
  "cache/views": "shared:files/view_cache"
  "cache/http": "shared:files/http_cache"
  "backups": "shared:files/backups"
  "Dropbox": "shared:files/dropbox"
  ".dropbox": "shared:files/dropbox-meta"

hooks:
  build: |
    wget "https://www.dropbox.com/download?plat=lnx.x86_64" -O archive.tar
    tar xzvf archive.tar && rm archive.tar
    gzip -k app/css/app.css
    gzip -k app/js/all.js
  deploy: |
    rm -rf cache/views/*

crons:
  db_backup:
    spec: "0 0 * * *"
    cmd: "php ./jobs/db_backup.php"