https://www.{default}/:
  cache:
    cookies: []
    default_ttl: 30
    enabled: true
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: false
  type: upstream
  upstream: app:http
https://{default}:
  to: http://www.{default}/
  type: redirect
